"""update builds table with remove warranty

Revision ID: 168fe5356209
Revises: 60fba279ccac
Create Date: 2026-10-03 12:40:32.322256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '168fe5356209'
down_revision: Union[str, Sequence[str], None] = '60fba279ccac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('builds', 'warranty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('warranty', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
