"""addfields for builds table

Revision ID: 3a936f3fdc9a
Revises: 168fe5356209
Create Date: 2026-10-04 13:01:31.936414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3a936f3fdc9a'
down_revision: Union[str, Sequence[str], None] = '168fe5356209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('cpu_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('builds', sa.Column('cpu_service_at', sa.Date(), nullable=True))
    op.add_column('builds', sa.Column('gpu_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('builds', sa.Column('gpu_service_at', sa.Date(), nullable=True))
    op.add_column('builds', sa.Column('ram_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('builds', sa.Column('ram_service_at', sa.Date(), nullable=True))
    op.add_column('builds', sa.Column('storage_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('builds', sa.Column('storage_service_at', sa.Date(), nullable=True))
    op.add_column('builds', sa.Column('psu_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('builds', sa.Column('psu_service_at', sa.Date(), nullable=True))
    op.add_column('builds', sa.Column('mainboard_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('builds', sa.Column('mainboard_service_at', sa.Date(), nullable=True))
    op.add_column('builds', sa.Column('cpu_cooler_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('builds', sa.Column('cpu_cooler_service_at', sa.Date(), nullable=True))
    op.add_column('builds', sa.Column('case_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('builds', sa.Column('case_service_at', sa.Date(), nullable=True))
    op.add_column('builds', sa.Column('os_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('builds', sa.Column('os_service_at', sa.Date(), nullable=True))
    op.drop_column('builds', 'mainboard')
    op.drop_column('builds', 'cpu_cooler')
    op.drop_column('builds', 'case')
    op.drop_column('builds', 'ram')
    op.drop_column('builds', 'gpu')
    op.drop_column('builds', 'os')
    op.drop_column('builds', 'psu')
    op.drop_column('builds', 'cpu')
    op.drop_column('builds', 'storage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('storage', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('builds', sa.Column('cpu', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('builds', sa.Column('psu', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('builds', sa.Column('os', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('builds', sa.Column('gpu', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('builds', sa.Column('ram', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('builds', sa.Column('case', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('builds', sa.Column('cpu_cooler', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('builds', sa.Column('mainboard', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('builds', 'os_service_at')
    op.drop_column('builds', 'os_name')
    op.drop_column('builds', 'case_service_at')
    op.drop_column('builds', 'case_name')
    op.drop_column('builds', 'cpu_cooler_service_at')
    op.drop_column('builds', 'cpu_cooler_name')
    op.drop_column('builds', 'mainboard_service_at')
    op.drop_column('builds', 'mainboard_name')
    op.drop_column('builds', 'psu_service_at')
    op.drop_column('builds', 'psu_name')
    op.drop_column('builds', 'storage_service_at')
    op.drop_column('builds', 'storage_name')
    op.drop_column('builds', 'ram_service_at')
    op.drop_column('builds', 'ram_name')
    op.drop_column('builds', 'gpu_service_at')
    op.drop_column('builds', 'gpu_name')
    op.drop_column('builds', 'cpu_service_at')
    op.drop_column('builds', 'cpu_name')
    # ### end Alembic commands ###
