"""make build type name unique

Revision ID: 60fba279ccac
Revises: da2251080514
Create Date: 2026-10-01 09:21:06.859179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '60fba279ccac'
down_revision: Union[str, Sequence[str], None] = 'da2251080514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_build_types_name'), table_name='build_types')
    op.create_index(op.f('ix_build_types_name'), 'build_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_build_types_name'), table_name='build_types')
    op.create_index(op.f('ix_build_types_name'), 'build_types', ['name'], unique=False)
    # ### end Alembic commands ###
