"""addfields for builds table

Revision ID: 6f54e0b95b44
Revises: 3a936f3fdc9a
Create Date: 2026-10-04 13:05:04.539283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6f54e0b95b44'
down_revision: Union[str, Sequence[str], None] = '3a936f3fdc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('sound_card_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('builds', sa.Column('sound_card_service_at', sa.Date(), nullable=True))
    op.drop_column('builds', 'sound_card')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('sound_card', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('builds', 'sound_card_service_at')
    op.drop_column('builds', 'sound_card_name')
    # ### end Alembic commands ###
