"""make build name unique

Revision ID: da2251080514
Revises: f0e2b34f734d
Create Date: 2026-10-01 09:18:41.166902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'da2251080514'
down_revision: Union[str, Sequence[str], None] = 'f0e2b34f734d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_builds_name'), 'builds', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_builds_name'), table_name='builds')
    # ### end Alembic commands ###
