"""create lifecycles table

Revision ID: db51f10fb6ee
Revises: 6575677490b8
Create Date: 2026-10-10 14:03:51.354753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'db51f10fb6ee'
down_revision: Union[str, Sequence[str], None] = '6f54e0b95b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifecycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('component_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('component_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.CheckConstraint('component_status BETWEEN 0 AND 2', name='check_component_status_range'),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifecycles_build_id'), 'lifecycles', ['build_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lifecycles_build_id'), table_name='lifecycles')
    op.drop_table('lifecycles')
    # ### end Alembic commands ###
