"""initial

Revision ID: f0e2b34f734d
Revises: 63c200f9988e
Create Date: 2026-09-30 18:47:43.221927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f0e2b34f734d'
down_revision: Union[str, Sequence[str], None] = '63c200f9988e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_types_name'), 'build_types', ['name'], unique=False)
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('build_type_id', sa.Integer(), nullable=False),
    sa.Column('cpu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gpu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ram', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('psu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mainboard', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu_cooler', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('os', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sound_card', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('warranty', sa.Date(), nullable=True),
    sa.Column('last_maintenance_at', sa.Date(), nullable=True),
    sa.Column('last_maintenance_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_maintenance_at', sa.Date(), nullable=True),
    sa.Column('next_maintenance_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['build_type_id'], ['build_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builds_build_type_id'), 'builds', ['build_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_builds_build_type_id'), table_name='builds')
    op.drop_table('builds')
    op.drop_index(op.f('ix_build_types_name'), table_name='build_types')
    op.drop_table('build_types')
    # ### end Alembic commands ###
