services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - vol-hardware-manager-db:/var/lib/mysql
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    restart: always

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./web:/web
      - /web/node_modules
    depends_on:
      - api
    restart: always

volumes:
  vol-hardware-manager-db:
