services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - vol-hardware-manager-db:/var/lib/mysql
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}

volumes:
  vol-hardware-manager-db: